"""
curer.py — Patch & file generator for detected structural failures.

All fixes are fully deterministic (no LLM generation).  The curer
produces ready-to-use files or a unified Git diff string, depending
on the selected output mode.

Supported cures
---------------
* Missing .gitignore  → language-specific file (Node or Python)
* Missing .env.example when .env exists → stripped .env.example
* Missing CI workflow → baseline GitHub Actions ci.yml
* Missing LICENSE → MIT license stub
"""

from __future__ import annotations

import os
import subprocess
import textwrap
from datetime import datetime
from pathlib import Path
from typing import Any

# -- .gitignore templates -----------------------------------------------------

_GITIGNORE_PYTHON = """\
# Byte-compiled / optimised Python
__pycache__/
*.py[cod]
*$py.class
*.pyo

# Distribution / packaging
.Python
build/
dist/
*.egg-info/
*.egg
.eggs/
sdist/
wheels/
MANIFEST

# Virtual environments
.venv/
venv/
ENV/
env/
.env

# Test artefacts
.pytest_cache/
.mypy_cache/
.tox/
htmlcov/
.coverage
coverage.xml
*.cover

# Jupyter
.ipynb_checkpoints/

# IDEs
.idea/
.vscode/
*.sublime-project
*.sublime-workspace

# OS
.DS_Store
Thumbs.db
"""

_GITIGNORE_NODE = """\
# Dependencies
node_modules/
jspm_packages/

# Build outputs
dist/
build/
out/
.next/
.nuxt/

# Environment
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Logs
logs/
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Cache
.cache/
.parcel-cache/
.eslintcache

# Test
coverage/
.nyc_output/

# IDEs
.idea/
.vscode/
*.sublime-project

# OS
.DS_Store
Thumbs.db
"""

_GITIGNORE_GENERIC = """\
# Environment secrets
.env
.env.*
!.env.example

# OS
.DS_Store
Thumbs.db

# IDEs
.idea/
.vscode/
"""

# -- CI workflow template -----------------------------------------------------

_CI_WORKFLOW = """\
# Generated by Repo Doctor — edit to fit your project
name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # -- Python ----------------------------------------------------------
      - name: Set up Python
        if: hashFiles('pyproject.toml') != '' || hashFiles('requirements*.txt') != ''
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        if: hashFiles('pyproject.toml') != '' || hashFiles('requirements*.txt') != ''
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt 2>/dev/null || pip install .

      - name: Run Python tests
        if: hashFiles('pyproject.toml') != '' || hashFiles('requirements*.txt') != ''
        run: |
          python -m pytest --tb=short -q 2>/dev/null || echo "No tests found"

      # -- Node ------------------------------------------------------------
      - name: Set up Node
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node dependencies
        if: hashFiles('package.json') != ''
        run: npm ci

      - name: Run Node tests
        if: hashFiles('package.json') != ''
        run: npm test --if-present
"""

# -- MIT License template -----------------------------------------------------

_MIT_LICENSE = """\
MIT License

Copyright (c) {year} {author}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""


# -- Helpers ------------------------------------------------------------------

def _detect_ecosystem(repo_root: Path) -> str:
    """Return 'python', 'node', or 'generic' based on top-level manifests."""
    names = {p.name for p in repo_root.iterdir()} if repo_root.is_dir() else set()
    if "package.json" in names:
        return "node"
    if any(n in names for n in ("pyproject.toml", "setup.py", "requirements.txt", "Pipfile")):
        return "python"
    return "generic"


def _strip_env(env_path: Path) -> str:
    """
    Read a .env file and return .env.example content with values stripped.

    Lines that are comments or blank are preserved.  Variable values are
    replaced with empty strings so the file is safe to commit.
    """
    lines: list[str] = []
    try:
        for raw_line in env_path.read_text(encoding="utf-8", errors="replace").splitlines():
            stripped = raw_line.strip()
            if not stripped or stripped.startswith("#"):
                lines.append(raw_line)
            elif "=" in stripped:
                key = stripped.split("=", 1)[0]
                lines.append(f"{key}=")
            else:
                lines.append(raw_line)
    except OSError:
        pass
    return "\n".join(lines) + "\n"


# -- Main Cure API -------------------------------------------------------------

class CureResult:
    """Accumulates generated file paths and their content."""

    def __init__(self) -> None:
        # {relative_path_str -> content_str}
        self._files: dict[str, str] = {}

    def add(self, rel_path: str, content: str) -> None:
        self._files[rel_path] = content

    @property
    def files(self) -> dict[str, str]:
        return dict(self._files)

    def write_to_disk(self, repo_root: Path) -> list[str]:
        """Write all generated files to disk; return list of written paths."""
        written: list[str] = []
        for rel_path, content in self._files.items():
            target = repo_root / rel_path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            written.append(str(target))
        return written

    def as_unified_diff(self, repo_root: Path) -> str:
        """
        Return a unified diff string (``git diff`` style) for all generated
        files.  Files that do not yet exist on disk are shown as additions
        from /dev/null.
        """
        diff_parts: list[str] = []
        for rel_path, new_content in self._files.items():
            target = repo_root / rel_path
            if target.exists():
                old_content = target.read_text(encoding="utf-8", errors="replace")
            else:
                old_content = ""

            old_lines = old_content.splitlines(keepends=True)
            new_lines = new_content.splitlines(keepends=True)

            import difflib
            diff = list(
                difflib.unified_diff(
                    old_lines,
                    new_lines,
                    fromfile=f"a/{rel_path}",
                    tofile=f"b/{rel_path}",
                )
            )
            if diff:
                diff_parts.extend(diff)

        return "".join(diff_parts)


def generate_cures(
    repo_root: Path,
    hygiene: dict[str, Any],
    secrets: dict[str, Any],
) -> CureResult:
    """
    Produce a :class:`CureResult` containing all applicable auto-fixes.

    Parameters
    ----------
    repo_root:
        Absolute path to the repository.
    hygiene:
        Result from :func:`repo_doctor.checks.git_hygiene.run`.
    secrets:
        Result from :func:`repo_doctor.checks.secrets.run`.

    Returns
    -------
    :class:`CureResult`
    """
    root = Path(repo_root).resolve()
    result = CureResult()
    ecosystem = _detect_ecosystem(root)

    # -- .gitignore -----------------------------------------------------------
    if not hygiene["has_gitignore"]:
        if ecosystem == "node":
            result.add(".gitignore", _GITIGNORE_NODE)
        elif ecosystem == "python":
            result.add(".gitignore", _GITIGNORE_PYTHON)
        else:
            result.add(".gitignore", _GITIGNORE_GENERIC)

    # -- .env.example ---------------------------------------------------------
    if secrets["has_dot_env"] and not secrets["has_dot_env_example"]:
        env_path = root / ".env"
        result.add(".env.example", _strip_env(env_path))

    # -- CI workflow -----------------------------------------------------------
    if not hygiene["has_ci"]:
        result.add(".github/workflows/ci.yml", _CI_WORKFLOW)

    # -- LICENSE ---------------------------------------------------------------
    if not hygiene["has_license"]:
        year = datetime.now().year
        # Try to guess author from git config
        try:
            author = subprocess.check_output(
                ["git", "config", "user.name"],
                cwd=str(root),
                stderr=subprocess.DEVNULL,
                timeout=3,
            ).decode().strip() or "Contributors"
        except Exception:
            author = "Contributors"
        result.add("LICENSE", _MIT_LICENSE.format(year=year, author=author))

    return result
